#!/bin/bash

if [ -d "$EXEC_CMD_DIR" ]; then 
    command_cfg="$EXEC_CMD_DIR/commands"
    help_file="$EXEC_CMD_DIR/commands_help" 
else
    command_cfg="$HOME/commands"
    help_file="$HOME/commands_help"
fi

DEBUG=false
PARAM_CHAR='!!'
SELF_REF='%self%'

[ -f "$EXEC_CMD_CFG" ] && . "$EXEC_CMD_CFG" ||
    ([ -f ~/.exec-cmd.rc ] && . ~/.exec-cmd.rc)

function process_cmd
{
    alias=$1
    cmd=$(grep "^\(\w\+,\)*$alias\(,\w\+\)*\s\+" <<< $commands | awk '{$1 = ""; print}')
    [ -z "$cmd" ] && echo "No such alias defined" && return
    params=$(grep -E -o "$PARAM_CHAR\w+" <<< $cmd) 
    args=( "$@" )
    arg_idx=1
    [[ "$params" ]] && 
    while read -r param ; do
        cmd=$(sed "s/$param/\"\${args[$arg_idx]}\"/g" <<< $cmd)
        ((arg_idx++))
    done <<< "$params"
    if (($# < $arg_idx)); then 
        echo "Required parameters: $params" | tr '\n' ' ' && echo
    else
        $DEBUG && set -x
        eval $cmd
        $DEBUG && set +x
    fi;
}

helptext="Need to provide a command or alias.\n\
        -h for general help,\n\
        -h <command> for a description of a specific command,\n\
        -c for a list of commands,\n
        -a for commands and aliases"

[ -z $1 ] && echo -e $helptext && exit 0

# ===== Preprocess command file ======
# 1. Combine lines with terminating \ characters,
#   - Create label :a
#   - Remove next occurrence of terminating \
#   - If nothing found, terminate sed script (T directive)
#   - Join with next line (N = append)
#   - Remove \n followed by leading space
#   - If successfully done above, proceed to :a (continue)
# 2. Remove comments at line start
# 3. Replace self references with full path to this executable
# 3. Strip out blank lines, 

commands=$(sed ':a;s/\\$//;T;N;s/\n\s*//;ta' $command_cfg |
           sed 's/^\s*#.*$//g; s&'"$SELF_REF&$0&"'g; /^\s*$/d')

while getopts "ach" o; do 
    case "${o}" in
        h) [[ $2 && -f $help_file ]] && sed -n "/^$2:/p" $help_file || 
            echo -e $helptext; exit 0;;
        c) sed 's/[,[:space:]].*//' <<< $commands; exit ;;
        a) sed 's/\s.*//; s/,/: /' <<< $commands ; exit ;;
    esac 
done

process_cmd "$@"
exit 0
